source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'pg'
gem 'puma'
gem 'carrierwave'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'haml-rails'
gem 'kaminari', '~> 0.16.3'

gem 'devise'
gem 'activeadmin', github: 'activeadmin'
gem 'select2-rails'
gem 'activeadmin-select2', github: 'mfairburn/activeadmin-select2'

gem 'grape', '~> 0.13.0'
gem 'grape_logging', '~> 1.1', '>= 1.1.2'
gem 'grape-swagger', '~> 0.10.2'
gem 'warden', '~> 1.2', '>= 1.2.3'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring' 
  gem 'rspec-rails'
  gem 'populator'
  gem 'annotate'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'fakeweb'
  gem 'fuubar'
end